"""empty message

Revision ID: 27f21dfce531
Revises: 8d751abc3d0
Create Date: 2015-01-09 11:09:15.195099

"""

# revision identifiers, used by Alembic.
revision = '27f21dfce531'
down_revision = '8d751abc3d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
